permalink:           pretty

# Setup
title:               'Masterplan'
tagline:             'Build it to share!'
baseurl:             'https://soburei.github.io/Masterplan'

sass:
  style: compressed

# About/contact
author:
  name:              osd
  url:               https://twitter.com/osd_it
  email:             contact@osd.tools

gems:                [algoliasearch-jekyll]

# Custom vars
version:             1.0.0

exclude:             [vendor]

github:
  repository_url:    https://github.com/soburei/Masterplan

twitter:
  handle:            osd_it

algolia:
  application_id:    'RJLGF63QKK'
  index_name:        'docs'
  read_only_api_key: 'c9e5cf2be0bd488a1e022c1f746f43c0'
  excluded_files:
    - 404.html

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "The Bakery"
